# src/upstream_analysis/config/default_config.yaml
# --- Default settings for the analysis library ---

parsing:
  bioreactor:
    decimal_separator: ','
    column_separator: ';'
    date_format: '%d.%m.%Y %H:%M'
    skiprows: 1
  offline:
    decimal_separator: '.'
    column_separator: ','
    date_format: 'guess'
    sheet_name: 0

# Standard Column Mapping (Override in run_config if needed)
column_mapping:
   # --- Online Data ---
   # 'Raw Header from CSV': standard_internal_name
   'Date Time UTC':                  date_time_utc
   'Date Local Time':                date_time_local
   'Batch Time, sec':                batch_time_sec
   'Batch Time (since inoc.), sec':  batch_time_since_inoc_sec
   'Phase':                          process_phase
   'Phase Time, sec':                phase_time_sec
   'Foam, -':                        foam
   'AirFlow, l/min':                 air_flow
   'TotalFlow, l/min':               total_flow
   'Gas2Flow, l/min':                o2_flow
   'GasMix':                         gas_mix
   'Pump1, %':                       acid_pump_pct
   'Pump1.Duration, -':              acid_pump_duration
   'Pump2, %':                       base_pump_pct
   'Pump2.Duration, -':              base_pump_duration
   'Pump3, %':                       inducer_pump_pct
   'Pump3.Duration, -':              inducer_pump_duration
   'Pump4, %':                       feed_pump_pct
   'Pump4.Duration, -':              feed_pump_duration
   'Stirrer, 1/min':                 stirrer_speed
   'Temperature, °C':                temperature # <-- Use the actual degree symbol if your file has it
   # If you still have encoding issues with '°', use the workaround:
#   'Temperature, Â°C':             temperature
   'Balance, g':                     balance
   'AnalogIO1, %':                   analog_io1
   'AnalogIO2, %':                   analog_io2
   'pH, -':                          ph
   'pO2, %':                         po2
   'GenericGasAnalyser.ExitCO2, %':  offgas_co2
   'GenericGasAnalyser.ExitO2, %':   offgas_o2
   'OD600':                          od600_online
   'ExponentialFeeding.Feedrate, %': feedrate_exp
   'FeedingInduction.Feedrate2, %':  feedrate_ind

   # --- Offline Data ---
   # 'Raw Header from Samples File': standard_internal_name
   'Process Time [h]':               process_time
   'Biomass [g/L]':                  biomass_g_l
   'Glucose [g/L]':                  glucose_g_l
   'Protein concentration [g/L]':    protein_g_l
   'Sample volume [mL]':             sample_volume_ml
   'Acetate [g/L]':                  acetate_g_l
   'Viability [%]':                  viability_pct
   'OD':                             od600

# Default Settings for Library Operation
cleaning:
  filter_preparation: true
  balance_tare_correction: true
  calculate_process_time: true
  median_filter: true
  median_filter_columns: ['balance']
  median_filter_window: 10
  median_filter_threshold: 10
  balance_tare_threshold: -100

alignment:
  online_time_col: 'process_time'
  offline_time_col: 'process_time'
  tolerance_hours: 0.1
  save_separate_samples_file: true
  force_align_last_sample: true

processing:
  constants:
    mw_glucose: 180.156 # Still useful as a general constant, though molar mass per C-mol is often more directly used.
  biomass_params: # Default biological properties
    elemental_composition_c_mol: { C: 1.0, H: 1.77, N: 0.24, O: 0.49 }
    molar_mass_g_c_mol: 26.565
    ash_fraction_g_g: 0.08
  product_params:
    name: null
    nitrogen_content_fraction: null
  induced_phases:
    - 'induced Fedbatch'
    - 'Induced fed batch'
    - 'Production'
  filtering: # Specific to feed calculations
    apply_feed_filter: true
    median_filter_window: 5
    median_filter_threshold: 10

# Placeholders
analysis: {}
visualization: {}