# src/data/config/default_config.yaml
# --- Default settings, expected to be overridden by experiment configs ---

parsing:
  bioreactor:
    decimal_separator: ','
    column_separator: ';'
    date_format: '%d.%m.%Y %H:%M' # Adjusted based on rawdata.csv
    skiprows: 1
  offline:
    decimal_separator: '.' # Default for typical offline files
    column_separator: ',' # Default for typical offline files
    date_format: 'guess'  # Let pandas guess by default
    sheet_name: 0         # Default sheet for Excel

# Add mappings for offline files as needed in experiment config.
column_mapping:
  date_time_utc: 'Date Time UTC'
  date_time_local: 'Date Local Time'
  batch_time_sec: 'Batch Time, sec'
  # Note: Processing step converts this sec value to h
  batch_time_since_inoc_h: 'Batch Time (since inoc.), sec'
  process_phase: 'Phase'
  phase_time_sec: 'Phase Time, sec'
  foam: 'Foam, -'
  air_flow: 'AirFlow, l/min'
  total_flow: 'TotalFlow, l/min'
  o2_flow: 'Gas2Flow, l/min' # Assuming Gas2 is O2
  gas_mix: 'GasMix'
  acid_pump_pct: 'Pump1, %' # Assumed mapping
  acid_pump_duration: 'Pump1.Duration, -'
  base_pump_pct: 'Pump2, %' # Assumed mapping
  base_pump_duration: 'Pump2.Duration, -'
  inducer_pump_pct: 'Pump3, %' # Assumed mapping
  inducer_pump_duration: 'Pump3.Duration, -'
  feed_pump_pct: 'Pump4, %' # Assumed mapping
  feed_pump_duration: 'Pump4.Duration, -'
  stirrer_speed: 'Stirrer, 1/min'
  temperature: 'Temperature, °C'
  balance: 'Balance, g'
  analog_io1: 'AnalogIO1, %'
  analog_io2: 'AnalogIO2, %'
  ph: 'pH, -'
  po2: 'pO2, %'
  offgas_co2: 'GenericGasAnalyser.ExitCO2, %'
  offgas_o2: 'GenericGasAnalyser.ExitO2, %'
  od600_online: 'OD600' # Keep OD600 mapping simple for online/offline potential
  feedrate_exp: 'ExponentialFeeding.Feedrate, %'
  feedrate_ind: 'FeedingInduction.Feedrate2, %'
  # --- Standardized names for offline data (add source patterns in exp. config if needed) ---
  process_time: 'Process Time [h]' # Default assumes hours directly
  biomass_g_l: 'Biomass [g/L]'
  glucose_g_l: 'Glucose [g/L]'
  protein_g_l: 'Protein concentration [g/L]'
  sample_volume_ml: 'Sample volume [mL]'
  acetate_g_l: 'Acetate [g/L]' # <<< NEW Standard Name Added
  viability_pct: 'Viability [%]' # <<< NEW Standard Name Added
  od600: 'OD' # Keep the simple OD600 from online mapping as primary default

cleaning:
  filter_preparation: true
  balance_tare_correction: true
  median_filter: true
  calculate_process_time: true # Creates 'process_time' column in hours
  balance_columns: ['balance'] # Use standardized name
  balance_tare_threshold: -100
  median_filter_columns: ['balance'] # Use standardized name
  median_filter_window: 20
  median_filter_threshold: 30

alignment:
  online_time_col: 'process_time' # Use standardized name
  offline_time_col: 'process_time' # Use standardized name
  tolerance_hours: 0.02

processing:
  # General physical/chemical constants (less likely to change per experiment)
  constants:
    mw_glucose: 180.156 # g/mol
    # Add other general constants if needed
  # Gas calculation defaults (can be overridden)
  gas_params:
    x_co2_in: 0.04    # mol%
    x_o2_in: 21.0     # mol%
    x_o2_wet: 20.89   # mol% (from your metadata example)
    mol_volume_air: 25.291 # L/mol (state T/P, e.g., @ 35°C)
  # Parameters requiring experiment-specific values (set to null in default)
  # The code using these MUST check if they are provided in the final merged config.
  feed_params:
    start_volume_ml: 1070
    feed_density: 1.15 # g/mL
    batch_medium_glucose: 20 # g/L
    feed_medium_glucose: 400 # g/L
  biomass_params:
    # Set defaults based on E. coli example, but can be overridden
    c_in_biomass: 24.5 # mmol C / g biomass
    elemental_composition: # mol/C-mol (based on your metadata)
      C: 1.0
      H: 1.77
      N: 0.24
      O: 0.49
    molar_mass_c_mol: 26.565 # g/C-mol (calculated from above)
  # --- Phases triggering induction ---
  induced_phases:
    - 'induced Fedbatch'
    - 'Induced fed batch'
    - 'Production' # Add other common names if needed
  filtering:
    apply_feed_filter: true # Default to OFF
    median_filter_window: 10  # Window specifically for feed balance filtering
    median_filter_threshold: 5 # Threshold specifically for feed balance filtering

# Placeholder sections
analysis: {}
visualization: {}